const REJECTION_REASONS = {
  FAKE_PHOTO:        'FAKE_PHOTO',
  INAPPROPRIATE:     'INAPPROPRIATE_CONTENT',
  INVALID_KYC:       'INVALID_KYC_DOCUMENT',
  UNDERAGE:          'APPEARS_UNDERAGE',
  DUPLICATE_ACCOUNT: 'DUPLICATE_ACCOUNT',
  INCOMPLETE:        'INCOMPLETE_PROFILE',
  OTHER:             'OTHER'
};

const USER_STATUS = {
  PENDING:      'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED:     'APPROVED',
  REJECTED:     'REJECTED'
};

module.exports = { REJECTION_REASONS, USER_STATUS };